
package com.ebay.services.productmetadata;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ProductMetadataService", targetNamespace = "http://www.ebay.com/marketplace/marketplacecatalog/v1/services", wsdlLocation = "ProductMetadataService.wsdl")
public class ProductMetadataService
    extends Service
{

    private final static URL PRODUCTMETADATASERVICE_WSDL_LOCATION;
    private final static WebServiceException PRODUCTMETADATASERVICE_EXCEPTION;
    private final static QName PRODUCTMETADATASERVICE_QNAME = new QName("http://www.ebay.com/marketplace/marketplacecatalog/v1/services", "ProductMetadataService");

    static {
        PRODUCTMETADATASERVICE_WSDL_LOCATION = com.ebay.services.productmetadata.ProductMetadataService.class.getResource("ProductMetadataService.wsdl");
        WebServiceException e = null;
        if (PRODUCTMETADATASERVICE_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find 'ProductMetadataService.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        PRODUCTMETADATASERVICE_EXCEPTION = e;
    }

    public ProductMetadataService() {
        super(__getWsdlLocation(), PRODUCTMETADATASERVICE_QNAME);
    }

    public ProductMetadataService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PRODUCTMETADATASERVICE_QNAME, features);
    }

    public ProductMetadataService(URL wsdlLocation) {
        super(wsdlLocation, PRODUCTMETADATASERVICE_QNAME);
    }

    public ProductMetadataService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PRODUCTMETADATASERVICE_QNAME, features);
    }

    public ProductMetadataService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ProductMetadataService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ProductMetadataServicePortType
     */
    @WebEndpoint(name = "ProductMetadataServiceSOAP12port_http")
    public ProductMetadataServicePortType getProductMetadataServiceSOAP12PortHttp() {
        return super.getPort(new QName("http://www.ebay.com/marketplace/marketplacecatalog/v1/services", "ProductMetadataServiceSOAP12port_http"), ProductMetadataServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ProductMetadataServicePortType
     */
    @WebEndpoint(name = "ProductMetadataServiceSOAP12port_http")
    public ProductMetadataServicePortType getProductMetadataServiceSOAP12PortHttp(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.ebay.com/marketplace/marketplacecatalog/v1/services", "ProductMetadataServiceSOAP12port_http"), ProductMetadataServicePortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PRODUCTMETADATASERVICE_EXCEPTION!= null) {
            throw PRODUCTMETADATASERVICE_EXCEPTION;
        }
        return PRODUCTMETADATASERVICE_WSDL_LOCATION;
    }

}
